# Generated by Django 3.2.3 on 2021-05-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('sid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('position', models.CharField(default='3', max_length=2)),
            ],
            options={
                'db_table': 'system_user',
            },
        ),
    ]
